# Generated by Django 4.2.6 on 2023-10-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_worker_offer_jobrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='jobytpe',
            new_name='jobType',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
