# Generated by Django 4.2.6 on 2023-10-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_jobytpe_offer_jobtype_delete_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='publicationDate',
            field=models.DateField(),
        ),
    ]
